### ISSUE TITLE
[BUG] Install via Octopi interface installs as "Unknown"; upon restart plugin not installed

### ISSUE THREAD

**Issue by thepancreator** [Willmac16/OctoPrint-GcodeLeveling#20]
**Describe the bug**
When trying to install via Octoprint web interface, the install goes normally and no errors are thrown. But upon server restart, the plugin doesn't show up under "Installed Plugins" and isn't usable. Note when installing via the interface, the confirmation popup that Octoprint shows says "Install 'Unknown' [checkmark]" before the usual request for server restart. 

**To Reproduce**
1. Open "Plugin Manager" in OctoPrint settings
2. Click on "add more"
3. Search "level"
4. Click "Install" next to "OctoPrint-GcodeLeveling"
5. Complete process (see txt file for log output and image clip of confirmation/restart required box popup)
6. Restart server, go to plugin manager to activate plugin, doesn't show up in installed plugins.

**Expected behavior**
For plugin to install and be visible in installed plugins, and to behave as intended.

**Screenshots**

**OctoPrint (please complete the following information):**
 - OS: OctoPi
 - OctoPrint Version: 1.10.3
 - OctoPi Version: 1.0.0cam
 - Python Version: 3.9.2

**Additional context**
Have gone through the usual `sudo apt-get update` and `sudo apt-get upgrade`, as well as individually installing the recommended `sudo apt install libatlas3-base`. No dice.

**Comment by Willmac16** [comment]
I'll take a look when I've got time in the next couple of days. Sounds like I'm probably using an outdated format to advertise the plugin to octoprint.

**Comment by thepancreator** [comment]
Forgot to actually add the files.
![octoprint gcodeleveling not in installed plugins](https://github.com/user-attachments/assets/7fa6cb36-5fcf-4c38-bf57-4c97b09be236)
![octoprint gcode leveler install unknown](https://github.com/user-attachments/assets/94d2cea6-33fb-4af9-a8ef-ee97614c8eb8)
[octoprint gcode leveling install output.txt](https://github.com/user-attachments/files/18142133/octoprint.gcode.leveling.install.output.txt)

**Comment by Willmac16** [comment]
I just installed onto a virtual environment w/ octoprint `1.10.3`  on python `3.12` without issue.

@thepancreator, Could you share a SystemInfo Bundle so I can take a further look?

**Comment by thepancreator** [comment]
Yep! See attached.
[octoprint-systeminfo-20241217212555.zip](https://github.com/user-attachments/files/18174331/octoprint-systeminfo-20241217212555.zip)

**Comment by Willmac16** [comment]
The only thing I see is that it seems like your system is currently voltage throttled. In addition to getting a high enough rating power supply, I would try increasing the log level to debug to see if anything is up.

<img width="631" alt="image" src="https://github.com/user-attachments/assets/2d70d0bb-10ea-41c9-914e-4796410720a7" />

**Comment by Willmac16** [comment]
I tried again on a 3.9 venv and had no issues. On the 3.12 venv I was seeing some warnings about regex escapes being wrong so installing from this url should fix that `https://github.com/Willmac16/OctoPrint-GcodeLeveling/archive/refs/heads/regex-fix.zip`, but I'm unsure that it would cause the type of install issue that you're seeing (and it would show up in the logs even on a info level trace).

**Comment by thepancreator** [comment]
I appreciate all of the help on this so far, given that it seems to be a unique problem I'm having. I'm also using an "Official"(?) Canakit power supply that should be giving 2.5A at 5V (which is still technically underpowered since the Pi wants 5.1V), so the throttling is also a little confusing.

**Comment by thepancreator** [comment]
Here's a new SystemInfo bundle, with a fresh install of OctoPi, a 5.1V 3A Official RPi power supply, and a fresh attempt at installing the plugin via the plugin manager. 
[octoprint-systeminfo-20241219214451.zip](https://github.com/user-attachments/files/18205671/octoprint-systeminfo-20241219214451.zip)

**Comment by thepancreator** [comment]
Also just tried installing with the link you provided, still showing up as "Unknown" like in the previous screen clipping, and not showing up in the "Installed plugins". 
[octoprint-systeminfo-20241219215038.zip](https://github.com/user-attachments/files/18205694/octoprint-systeminfo-20241219215038.zip)

**Comment by Willmac16** [comment]
The Throttle state could also be a thermal throttle, but it doesn't seem to be showing up on the recent bundles. So probably not something to worry about.

Looks like we got the error to show up finally!

```bash
Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.9 from "/home/narab/oprint/bin/python"
  * The NumPy version is: "2.0.2"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: libopenblas.so.0: cannot open shared object file: No such file or directory
```

Solution will likely be to install openblas w/
```bash
sudo apt install libopenblas-dev
```


If the underlying error is fixed this should print 0 through 9:

```bash
/home/narab/oprint/bin/python -c 'import numpy as np; print(np.arange(10))'
```

It looks like the numpy docs referenced by the error point to
```bash
sudo apt-get install libatlas-base-dev
```

So maybe give that a go if the libopenblas doesn't work. And let me know what ultimately works so I can add it to the install recommendations.

**Comment by thepancreator** [comment]
That did it! Running `sudo apt install libopenblas-dev` completed without issue, and I was able to generate `[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]` using `/home/narab/oprint/bin/python -c 'import numpy as np; print(np.arange(10))'`. Upon system reboot and installing the plugin again through the normal Manager method, it now correctly shows up in the Plugin Management Log popup as "Install _GcodeLeveling_". I did not need to run the additional step of `sudo apt-get install libatlas-base-dev` for it to function.
